### ISSUE TITLE
Error: ERR_DISALLOWED_URL_SCHEME

### ISSUE THREAD

**Issue by pmulgaonkar** [jizhang/logviewer#1]
I am trying to get this basic code to work. I run the server on a local VM using: python3 server.py --host 192.168.1.28 --port 5000 --prefix /var/log/supervisord since I am trying to tail the logs from /var/log/supervisord/error.log. Then on a chrome browser, I try ws://192.168.1.28:5000/var/log/supervisord/error.log?tail=1

However I don't get anything. Developer console/Network tab does not show anything meaningful. logging/print statements in the view_log function don't show it being called at all. What am I missing. There is no nginx or anything else running on the server that could be interfering.

The output on the browser is:
The webpage at ws://192.168.1.28:5000/var/log/supervisord/error.log might be temporarily down or it may have moved permanently to a new web address.
ERR_DISALLOWED_URL_SCHEME

**Comment by jizhang** [comment]
I add a demo client. Please check out the readme for details.
